repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
            -   id: trailing-whitespace
            -   id: check-merge-conflict
            -   id: end-of-file-fixer
            -   id: check-added-large-files
            -   id: check-case-conflict
            -   id: check-json
            -   id: check-vcs-permalinks
            -   id: mixed-line-ending
            -   id: pretty-format-json
                args:
                  - --autofix
                  - --indent=4
                  - --top-keys=php
            -   id: check-yaml
            -   id: sort-simple-yaml
                files: '.yml$'
            -   id: sort-simple-yaml
                files: '.yaml$'
            -   id: check-symlinks
            -   id: detect-private-key
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.6
    hooks:
    -   id: remove-tabs
    -   id: remove-crlf
