before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --$COMPOSER_CHANNEL
  - composer --version
  - php -i
services:
  - mysql
env:
  global:
    - SIMPLETEST_DB=sqlite://tmp/site.sqlite
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
    - COMPOSER_MEMORY_LIMIT=-1
  matrix:
    - RELEASE=stable COMPOSER_CHANNEL=stable
#    - RELEASE=stable COMPOSER_CHANNEL=snapshot

install:
  - composer --verbose validate
  - composer --verbose update

jobs:
  include:
    - stage: lint
      php: 7.3
      env: {}
      script:
        - source /home/travis/virtualenv/python3.6/bin/activate
        - pip install pre-commit
        - pre-commit run -a
    - stage: test

language: php
dist: xenial
sudo: false

php:
  - 7.2
  - 7.3
  - 7.4

script:
  - ./vendor/bin/drush site-install --verbose --yes --db-url=mysql://root:@localhost/drupal
  - ./vendor/bin/drush runserver $SIMPLETEST_BASE_URL &
  - cd web
  - until curl -s $SIMPLETEST_BASE_URL; do true; done > /dev/null
  - ./../vendor/bin/phpunit -c core --testsuite unit --group Pacifica
  - ./../vendor/bin/drush

stages:
  - lint
  - test
